## Numpy and Basic coding
Learning about Numpy from python 

In [13]:
import numpy as np

### Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1,2,3,4,5], ["Mayank", "Chotu", "Soahum", "Moksh", "Vaibhav"]])
print("2D Array: ", arr_2d)

1D Array:  [1 2 3 4 5]
2D Array:  [['1' '2' '3' '4' '5']
 ['Mayank' 'Chotu' 'Soahum' 'Moksh' 'Vaibhav']]


### List vs Numpy array

In [7]:
py_list = [1,2,3,4,5] # multiply the whole list 
print("Python List multiplication: ", py_list * 2)

np_array = np.array([1,2,3,4,5]) # multiply the elements in the array
print("Python Array Multiplication: ", np_array * 2)

Python List multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python Array Multiplication:  [ 2  4  6  8 10]


In [14]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation time:", time.time() - start)


 List Operation time: 0.13947319984436035

 Numpy Operation time: 0.01587533950805664


### Creating array using Numpy

In [22]:
zeros = np.zeros((3, 4))
print("Array of Zeros:\n", zeros)

ones = np.ones((3,4))
print("\nArray of Ones:\n", ones)

full = np.full((3,4), 7)
print("\nArray of Constant numbers:\n", full)

random = np.random.random((3,4))
print("\nArray of Random elements:\n", random)

sequence = np.arange(0,11,2)
print("\nArray of even numbers:\n", sequence)


Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of Constant numbers:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Array of Random elements:
 [[0.3189193  0.98744733 0.66726807 0.68180284]
 [0.77604255 0.7933039  0.43406907 0.89090544]
 [0.37983039 0.61997649 0.11020134 0.90787642]]

Array of even numbers:
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [24]:
vector = np.array([1,2,3,4,5])
print("Vector: ", vector)

matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
print("\nMatrix:\n", matrix)

tensor = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                   [[11,12,13,14,15], [16,17,18,19,20]]])
print("\nTensor:\n", tensor)

Vector:  [1 2 3 4 5]

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Tensor:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


### Array Properties

In [25]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array:\n", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array:\n", reshaped)

flattered = reshaped.flatten()
print("\nFlattern array:\n", flattered)

# returns view, instead of copy
raveled = reshaped.ravel()
print("\nRaveled array:\n", raveled)

transpose = reshaped.T
print("\nTranspose array:\n", transpose)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattern array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravel array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
