## Numpy Array Operations

In [1]:
import numpy as np

In [ ]:
arr_1d = np.arange(11)

print("Basic slicing:", arr_1d[2:9])
print("\nWith steps:", arr_1d[1:8:2])
print("\nNegative Indexing:", arr_1d[-3])

Basic slicing: [2 3 4 5 6 7 8]

With steps: [1 3 5 7]

Negative Indexing: 8


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Elements:", arr_2d[1,2])
print("\nEntire row:", arr_2d[1])
print("\nEntire coloumn:", arr_2d[:,2])

Specific Elements: 6

Entire row: [4 5 6]

Entire coloumn: [3 6 9]


### Sorting

In [28]:
Unsorted_array = np.random.random((4,5))
print("Unsorted Array:\n", Unsorted_array)
print("\nSorted Array:\n", np.sort(Unsorted_array))

Unsorted_array2 = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("\nSorted 2d array by coloumn:\n", np.sort(Unsorted_array, axis=0))
print("\nSorted 2d array by row:\n", np.sort(Unsorted_array, axis=1))

Unsorted Array:
 [[0.20530688 0.04920853 0.06939225 0.14139873 0.35480324]
 [0.56371746 0.3324585  0.75938158 0.93285549 0.92812724]
 [0.27175803 0.05323337 0.83672125 0.66908692 0.04587644]
 [0.65299657 0.83566711 0.82981619 0.77994603 0.59525738]]

Sorted Array:
 [[0.04920853 0.06939225 0.14139873 0.20530688 0.35480324]
 [0.3324585  0.56371746 0.75938158 0.92812724 0.93285549]
 [0.04587644 0.05323337 0.27175803 0.66908692 0.83672125]
 [0.59525738 0.65299657 0.77994603 0.82981619 0.83566711]]

Sorted 2d array by coloumn:
 [[0.20530688 0.04920853 0.06939225 0.14139873 0.04587644]
 [0.27175803 0.05323337 0.75938158 0.66908692 0.35480324]
 [0.56371746 0.3324585  0.82981619 0.77994603 0.59525738]
 [0.65299657 0.83566711 0.83672125 0.93285549 0.92812724]]

Sorted 2d array by row:
 [[0.04920853 0.06939225 0.14139873 0.20530688 0.35480324]
 [0.3324585  0.56371746 0.75938158 0.92812724 0.93285549]
 [0.04587644 0.05323337 0.27175803 0.66908692 0.83672125]
 [0.59525738 0.65299657 0.77994603 0.8

### Filtering

In [41]:
num = np.array([1,2,3,4,5,6,7,8,9,10,11])
even_numbers = num[num % 2 == 0]
odd_numbers = num[num % 2 != 0]
print("Even Numbers Array:", even_numbers)
print("\nOdd Numbers Array:", odd_numbers)

Even Numbers Array: [ 2  4  6  8 10]

Odd Numbers Array: [ 1  3  5  7  9 11]


### Filtering With Mask

In [43]:
mask = num > 5 
mask_2 = num <  5
print("Number Greater than 5:", num[mask])
print("Number smaller than 5:", num[mask_2])

Number Greater than 5: [ 6  7  8  9 10 11]
Number smaller than 5: [1 2 3 4]


### Fancy Indexing vs np.where()

In [50]:
indices = [0,2,4]
print("Indiced Array:", num[indices])

where_result = np.where(num > 6)
print("\nValue that stored in where :", where_result)
print("\nNP where:", num[where_result])

Indiced Array: [1 3 5]

Value that stored in where : (array([ 6,  7,  8,  9, 10]),)

NP where: [ 7  8  9 10 11]


In [52]:
condition_array = np.where(num >= 5, num * 3, num)
print(condition_array)

[ 1  2  3  4 15 18 21 24 27 30 33]


### Adding or Removing Data

In [58]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([1,2,3,4,5,6,7,8,9])

Combined = np.concatenate((arr_1, arr_2))
print("Combination of both arrays are:", Combined)

deleted = np.delete(arr_3, 3)
print("\nArray after deletion:", deleted)

Combination of both arrays are: [1 2 3 4 5 6]

Array after deletion: [1 2 3 5 6 7 8 9]


### Array Compatiblity

In [54]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([8,9,10,12])

print("Compatiblities of Array 1 and 2:", arr1.shape == arr2.shape)
print("Compatiblities of Array 2 and 3:", arr2.shape == arr3.shape)
print("Compatiblities of Array 3 and 1:", arr3.shape == arr1.shape)

Compatiblities of Array 1 and 2: True
Compatiblities of Array 2 and 3: False
Compatiblities of Array 3 and 1: False


### Adding new Row and Columns

In [56]:
original = np.array([[1,2,3,4,5],
                     [6,7,8,9,10]])

new_row = np.array([11,12,13,14,15])
new_col = np.array([[15], [20]])

# Adding new row
with_new_row = np.vstack((original, new_row))
print("Original Array:\n", original)
print("\nArray after new row:\n", with_new_row)

# Adding new column
with_new_col = np.hstack((original, new_col))
print("\nArray after new column:\n", with_new_col)


Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Array after new row:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Array after new column:
 [[ 1  2  3  4  5 15]
 [ 6  7  8  9 10 20]]
